CREATE TABLE TB_STATUS(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(25) NOT NULL
);

INSERT INTO TB_STATUS(STATUS)VALUES('PENDENTE');
INSERT INTO TB_STATUS(STATUS)VALUES('REALIZADO');

CREATE TABLE TB_TAREFAS(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_STATUS INT NOT NULL DEFAULT 1,
    FOREIGN KEY(ID_STATUS) REFERENCES TB_STATUS(ID),
	TAREFA TEXT NOT NULL,
    DATA_CADASTRADO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)